### ISSUE TITLE
Validation doesn't work 

### ISSUE THREAD

**Issue by keedle** [ryntab/vue-formulate-currency#1]
Hi,
Great package ♥ but for some reason my validation rules don't work.

`<FormulateInput
            type="currency"
            precision="0"
            currencyPrefix="£"
            name="loan"
            placeholder="Loan Amount £"
            validation="bail|required|number|min:10000,length"
            :validation-messages="{
              required: 'Please provide loan amount',
              min: 'Loan amount should be greater than £10,000',
            }"
          >
          </FormulateInput>`

**Comment by ryntab** [comment]
Hello! There is currently no validation support for this plugin, besides the most basic of requiring a value be set. I will add support for minimum and maximum values right away. 

Side note `precision="0"` should be `:precision="0"` the vue-numeric prop expects an integer not a string.

**Comment by ryntab** [comment]
Range validations have been added. Bit of an oversight on my part, glad you caught this.

Your example would now be the following...
```vue
<FormulateInput type="currency" error-behavior="live" :precision="0" currencyPrefix="£" name="loan" placeholder="Loan Amount £" validation="bail|required|number|min:10000" :validation-messages="{ required: 'Please provide loan amount', min: 'Loan amount should be greater than £10,000'}" />
```
You can also set a maximum value `min:999999`
